server:
    port: 9300

spring:
    application:
        name: logback-logstash-demo

    logstash:
        server: 10.160.10.51

logback:
    path: ${user.home}/logs
    maxFileSize: 10MB
    maxHistory: 90
    level: INFO
    fileName: demo
